# Generated by Django 4.2.23 on 2025-12-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('authority', models.CharField(max_length=50)),
                ('refid', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('error', 'ERROR'), ('complete', 'Completed')], max_length=20)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.invoice')),
            ],
        ),
    ]
